# Generated by Django 3.2.12 on 2022-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_review_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_hyperlink',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_code',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
