# Generated by Django 3.2.12 on 2022-03-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_project.jpg', null=True, upload_to=''),
        ),
    ]
